/*
 * TestBeanFrameComponents.java
 *
 *
 */
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import sferyx.administration.editors.*;
import javax.swing.text.*;
import javax.swing.text.html.*;

/**
 *
 * @author  Vassil Boyadjiev
 */
public class CustomTagsExample extends javax.swing.JFrame {

    /** Creates new form TestBeanFrame */
    public CustomTagsExample() {
        initComponents();
        hTMLEditor1.setXMLMode(true);
        hTMLEditor1.setContent("<html><head><style>my_custom_block_tag{background-color:red}</style></head><body><p>Some text here: <my_empty_tag/></p><my_custom_block_tag>Block tag content here</my_custom_block_tag><br></body></html>");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        hTMLEditor1 = new sferyx.administration.editors.HTMLEditor();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        hTMLEditor1.setRemovedMenuItems("");
        hTMLEditor1.setStatusMessage("");
        hTMLEditor1.setTableItemsStatus(false);
        getContentPane().add(hTMLEditor1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      // CustomXMLTagsGrammarSpecification.setTreatAllBlockTagsAsBlocks(true);
     // sferyx.administration.editors.CustomXMLTagsGrammarSpecification.registerCustomXMLTag("my_empty_tag",true);
      //sferyx.administration.editors.CustomXMLTagsGrammarSpecification.registerCustomXMLTag("my_custom_block_tag",false);
       sferyx.administration.editors.CustomXMLTagsGrammarSpecification.registerEmptyCustomXMLTagComponentRepresentation("my_empty_tag","MyCustomEmptyTag");
       
       CustomTagsExample frame=new CustomTagsExample();
      
       frame.setLocation(100,100);
       frame.setSize(800,600);
       frame.show();
    }

  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sferyx.administration.editors.HTMLEditor hTMLEditor1;
    // End of variables declaration//GEN-END:variables

 
   

}





