/*
 * InternationalizationExample.java
 *
 *
 */
import java.awt.*;

/**
 *
 * @author  Vassil Boyadjiev
 */
public class InternationalizationExample extends javax.swing.JFrame {

    
     static
     {
            try
      {
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
       
      }
      catch(Exception exc)
      {
      }  
     }
    
    /** Creates new form InternationalizationExample */
    public InternationalizationExample() {
        initComponents();
    setSize(370,650);
      setLocation(850,200);
        //The location of the language file should be a fully qualified URL
        hTMLEditor1.loadInterfaceLanguageFile(getClass().getResource("/sferyx/administration/editors/icons/sample-german-translation.txt").toString());//"sferyx/administration/editors/icons/sample-german-translation.txt");
        hTMLEditor1.setContent("The UI of the editor is translated in German with a sample translation file. You can load your own translation files if needed and change the menus, toolbars and other item names as you whish");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        hTMLEditor1 = new sferyx.administration.editors.HTMLEditor();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(hTMLEditor1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        InternationalizationExample intEx=new InternationalizationExample();
        intEx.setSize(700,500);
        intEx.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2-intEx.getWidth()/2,Toolkit.getDefaultToolkit().getScreenSize().height/2-intEx.getHeight()/2);
        intEx.show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sferyx.administration.editors.HTMLEditor hTMLEditor1;
    // End of variables declaration//GEN-END:variables

}
